ejercicio 9. mostrar llamada curl app.py

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -99,6 +99,19 @@ jobs: ## contenedor de todas las tareas. Aquí puedes tener varios (ej: ci, test
 
           echo -e "\n--- VOLÚMENES ---"
           docker volume ls      
+      - name: "Test E2E con curl"
+        run: |
+          echo "🌐 Realizando petición a la API en el puerto 5001..."
+          # Usamos -s (silent) para evitar la barra de progreso y -S para mostrar errores
+          RESPONSE=$(curl -sS --fail http://localhost:5001)
+          echo "📩 Respuesta recibida: $RESPONSE"
+          
+          if [ "$RESPONSE" == "Hola Mundo desde Flask!" ]; then
+            echo "✅ El servicio está respondiendo correctamente."
+          else
+            echo "❌ ERROR: Respuesta inesperada del servidor."
+            exit 1
+          fi     
       - name: "Cleanup"
         if: always() ## siempre se ejecuta
         run: |
